web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - .:/var/www/html
db:
  image: "mysql:5"
  volumes:
    - ./pingpong.sql:/tmp/pingpong.sql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "pingpong"
